version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"

  apicurio:
    image: "apicurio/apicurio-registry-mem:2.4.4.Final"
    ports:
      - "8080:8080"
